/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_springframework_core_type_classreading_SimpleMetadataReader */

#ifndef _Included_org_springframework_core_type_classreading_SimpleMetadataReader
#define _Included_org_springframework_core_type_classreading_SimpleMetadataReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_springframework_core_type_classreading_SimpleMetadataReader
 * Method:    decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_springframework_core_type_classreading_SimpleMetadataReader_decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
