/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_springframework_core_LocalVariableTableParameterNameDiscoverer_ParameterNameDiscoveringVisitor */

#ifndef _Included_org_springframework_core_LocalVariableTableParameterNameDiscoverer_ParameterNameDiscoveringVisitor
#define _Included_org_springframework_core_LocalVariableTableParameterNameDiscoverer_ParameterNameDiscoveringVisitor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
